// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplyController from "./apply_controller"
application.register("apply", ApplyController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchOffersController from "./search_offers_controller"
application.register("search-offers", SearchOffersController)

import { Application } from '@hotwired/stimulus'
import ScrollProgress from 'stimulus-scroll-progress'

const application = Application.start()
application.register('scroll-progress', ScrollProgress)
